# c:\Users\Anahi\PRUEBAS_30728\backend\alembic\script.py.mako
"""add primer_ingreso usuario

Revision ID: 7595e4d8e8c0
Revises: f9d1c8e7b2a1
Create Date: 2026-07-15 16:35:22.155916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7595e4d8e8c0'
down_revision = 'f9d1c8e7b2a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('primer_ingreso', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'primer_ingreso')
    # ### end Alembic commands ###
