# c:\Users\Anahi\PRUEBAS_30728\backend\alembic\script.py.mako
"""add campos adicionales usuario (placa, numero_ruta, nombre_ruta, fotografia)

Revision ID: b7f3a9c2d1e4
Revises: 7595e4d8e8c0
Create Date: 2026-07-15 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f3a9c2d1e4'
down_revision = '7595e4d8e8c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('placa', sa.String(20), nullable=True))
    op.add_column('usuarios', sa.Column('numero_ruta', sa.String(50), nullable=True))
    op.add_column('usuarios', sa.Column('nombre_ruta', sa.String(100), nullable=True))
    op.add_column('usuarios', sa.Column('fotografia', sa.String(500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fotografia')
    op.drop_column('usuarios', 'nombre_ruta')
    op.drop_column('usuarios', 'numero_ruta')
    op.drop_column('usuarios', 'placa')
    # ### end Alembic commands ###
