# c:\Users\Anahi\PRUEBAS_30728\backend\alembic\script.py.mako
"""Initial migration - crear todas las tablas

Revision ID: a16670a825ec
Revises: 
Create Date: 2026-04-26 15:40:05.458101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16670a825ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('padre', 'conductor', 'dueno', 'admin', name='rol_usuario'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('llegada', 'salida', 'pago', 'alerta', name='tipo_notificacion'), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_table('recorridos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('dueno_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dueno_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recorridos_dueno_id'), 'recorridos', ['dueno_id'], unique=False)
    op.create_index(op.f('ix_recorridos_id'), 'recorridos', ['id'], unique=False)
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorrido_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('ida', 'vuelta', 'ida_vuelta', name='tipo_ruta'), nullable=False),
    sa.ForeignKeyConstraint(['recorrido_id'], ['recorridos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_id'), 'rutas', ['id'], unique=False)
    op.create_index(op.f('ix_rutas_recorrido_id'), 'rutas', ['recorrido_id'], unique=False)
    op.create_table('paradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paradas_id'), 'paradas', ['id'], unique=False)
    op.create_index(op.f('ix_paradas_ruta_id'), 'paradas', ['ruta_id'], unique=False)
    op.create_table('sesiones_ruta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('en_curso', 'completada', 'cancelada', name='estado_sesion_ruta'), nullable=False),
    sa.ForeignKeyConstraint(['conductor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_ruta_conductor_id'), 'sesiones_ruta', ['conductor_id'], unique=False)
    op.create_index(op.f('ix_sesiones_ruta_id'), 'sesiones_ruta', ['id'], unique=False)
    op.create_index(op.f('ix_sesiones_ruta_ruta_id'), 'sesiones_ruta', ['ruta_id'], unique=False)
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('padre_id', sa.Integer(), nullable=False),
    sa.Column('recorrido_id', sa.Integer(), nullable=False),
    sa.Column('parada_id', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['padre_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parada_id'], ['paradas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorrido_id'], ['recorridos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumnos_id'), 'alumnos', ['id'], unique=False)
    op.create_index(op.f('ix_alumnos_padre_id'), 'alumnos', ['padre_id'], unique=False)
    op.create_index(op.f('ix_alumnos_parada_id'), 'alumnos', ['parada_id'], unique=False)
    op.create_index(op.f('ix_alumnos_recorrido_id'), 'alumnos', ['recorrido_id'], unique=False)
    op.create_table('ubicaciones_gps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_ruta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ubicaciones_gps_id'), 'ubicaciones_gps', ['id'], unique=False)
    op.create_index(op.f('ix_ubicaciones_gps_sesion_id'), 'ubicaciones_gps', ['sesion_id'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('hora_subida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_bajada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('presente', 'ausente', 'tarde', name='estado_asistencia'), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_ruta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_alumno_id'), 'asistencias', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_asistencias_id'), 'asistencias', ['id'], unique=False)
    op.create_index(op.f('ix_asistencias_sesion_id'), 'asistencias', ['sesion_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('padre_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'pagado', 'vencido', name='estado_pago'), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['padre_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_alumno_id'), 'pagos', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_index(op.f('ix_pagos_padre_id'), 'pagos', ['padre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_padre_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_alumno_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_asistencias_sesion_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_id'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_alumno_id'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_ubicaciones_gps_sesion_id'), table_name='ubicaciones_gps')
    op.drop_index(op.f('ix_ubicaciones_gps_id'), table_name='ubicaciones_gps')
    op.drop_table('ubicaciones_gps')
    op.drop_index(op.f('ix_alumnos_recorrido_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_parada_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_padre_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_id'), table_name='alumnos')
    op.drop_table('alumnos')
    op.drop_index(op.f('ix_sesiones_ruta_ruta_id'), table_name='sesiones_ruta')
    op.drop_index(op.f('ix_sesiones_ruta_id'), table_name='sesiones_ruta')
    op.drop_index(op.f('ix_sesiones_ruta_conductor_id'), table_name='sesiones_ruta')
    op.drop_table('sesiones_ruta')
    op.drop_index(op.f('ix_paradas_ruta_id'), table_name='paradas')
    op.drop_index(op.f('ix_paradas_id'), table_name='paradas')
    op.drop_table('paradas')
    op.drop_index(op.f('ix_rutas_recorrido_id'), table_name='rutas')
    op.drop_index(op.f('ix_rutas_id'), table_name='rutas')
    op.drop_table('rutas')
    op.drop_index(op.f('ix_recorridos_id'), table_name='recorridos')
    op.drop_index(op.f('ix_recorridos_dueno_id'), table_name='recorridos')
    op.drop_table('recorridos')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
